import { BrowserWindowConstructorOptions, WebPreferences } from "electron";
import path from "path";

const preferenciasWeb: WebPreferences = {
    devTools: true,
    nodeIntegration: true,
    nodeIntegrationInWorker: false,
    nodeIntegrationInSubFrames: false,
    preload: path.join(__dirname,'..','appfront','preload.js'),
    sandbox: false,
    session: undefined,
    partition: undefined,
    zoomFactor: 1,
    javascript: true,
    webSecurity: true,
    allowRunningInsecureContent: false,
    images: true,
    imageAnimationPolicy: 'animate',
    textAreasAreResizable: true,
    webgl: true,
    plugins: false,
    experimentalFeatures: false,
    scrollBounce: false,
    enableBlinkFeatures: undefined,
    disableBlinkFeatures: undefined,
    defaultFontFamily: undefined,
    defaultFontSize: 16,
    defaultMonospaceFontSize: 13,
    minimumFontSize: 0,
    defaultEncoding: `ISO-8859-1`,
    backgroundThrottling: true,
    offscreen: false,
    contextIsolation: true,
    webviewTag: false,
    additionalArguments: undefined,
    safeDialogs: false,
    safeDialogsMessage: undefined,
    disableDialogs: false,
    navigateOnDragDrop: false,
    autoplayPolicy: 'no-user-gesture-required',
    disableHtmlFullscreenWindowResize: false,
    accessibleTitle: undefined,
    spellcheck: true,
    enableWebSQL: true,
    v8CacheOptions: 'none',
    enablePreferredSizeMode: false,
  }

export const optionsWindow: BrowserWindowConstructorOptions = {
    width: undefined,
    height: undefined,
    x: undefined,
    y: undefined,
    useContentSize: false,
    center: true,
    minWidth: 0,
    minHeight: 0,
    maxWidth: Infinity,
    maxHeight: Infinity,
    resizable: true,
    movable: true,
    minimizable: true,
    maximizable: true,
    closable: true,
    alwaysOnTop: false,
    fullscreen: false,
    fullscreenable: true,
    skipTaskbar: false,
    kiosk: false,
    title: 'Aqui debes escribir el titulo',
    icon: undefined,
    show: true,
    frame: true,
    parent: undefined,
    modal: false,
    acceptFirstMouse: false,
    disableAutoHideCursor: false,
    autoHideMenuBar: false,
    backgroundColor: '#559',
    hasShadow: true,
    enableLargerThanScreen: false,
    webPreferences:preferenciasWeb
};